# This is a basic workflow to help you get started with Actions

name: Updat test.html with current time

# Controls when the workflow will run
on: # 작업을 실행할 이벤트를 정의
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push: # code가 push 될 때 실행
    branches: [ "main" ]

jobs: # 작업을 정의
  build:
    runs-on: ubuntu-latest # 실행 환경 지정

    steps: # 작업 내에서 실행할 단계를 정의
      - uses: actions/checkout@v2 # repository checkout
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Set up python # python 설치
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Dependencies # 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python script # python script 실행
        run: |
          python update_time.py
      - name: Commit updated index.html # commit
        uses: EndBug/add-and-commit@v7 # 파일을 추가하고 commit
        with:
          author_name : "james"
          author_email : "joik1122@gmail.com"
          message : "Update index.html with current time"
          add: "index.html" # 변경된 파일 추가