name: Update index.html with current time

on: 
  push: 
    branches: [ "main" ]

jobs: 
  build:
    runs-on: ubuntu-latest 

    steps: 
      - uses: actions/checkout@v2 
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python script
        run: |
          python update_time.py
      - name: Commit updated index.html
        uses: EndBug/add-and-commit@v7
        with:
          author_name: James
          author_email: joik1122@gmail.com
          message: Update index.html with current time
          add: "index.html"
        env:
          GIT_COMMITTER_NAME: James
          GIT_COMMITTER_EMAIL: joik1122@gmail.com
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
