name: Update index.html with current time

on: 
  push: 
    branches: [ "main" ]

jobs: 
  build:
    runs-on: ubuntu-latest 

    steps: 
      - uses: actions/checkout@v2 
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python script
        run: |
          python update_time.py
      - name: Commit updated index.html
        run: |
          git config --global user.name 'james'
          git config --global user.email 'joik1122@gmail.com'
          git add index.html
          git commit -m "Update index.html with current time"
          git push https://github.com/${{ secrets.GIT_TOKEN }}@github.com/joik1122/github-action-test.git
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
